### ISSUE TITLE
having difficulties using servicePort that isn't 80

### ISSUE THREAD

**Issue by remster** [koli/kong-ingress#16]
is there a known problem/limitation with it?

**Comment by cainelli** [comment]
Hey @remster, can you send the service and ingress yml you're using?

The logs from kong-ingress controller would also be useful.

**Comment by sandromello** [comment]
Hi remster,

Indeed there is, I will make a quick test here just to be sure.

**Comment by remster** [comment]
```
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: sample-service
        image: sample-service:0.0
        env:
          - name: PORT
            value: "3000"
---
kind: Service
apiVersion: v1
metadata:
  name: sample-service
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: sample-service
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-service-ingress
  annotations:
    kolihub.io/acme.local: primary
spec:
  rules:
  - host: remek.ele
    http:
      paths:
      - path: /ele
        backend:
          serviceName: sample-service
          servicePort: 3000

```

sorry - dunno how to harvest logs from the kong-ingress controller
